# include all R packages in your project
library(devtools)
library(knitr)
library(xtable)
library(ggplot2)
library(shiny)
library(stringr)
library(MASS)
library(tree)
library(VIM)
library(caret)
library(mice)
library(gbm)
library(corrplot)

sink("../../session-info.txt", append = TRUE)
cat("Session Information\n\n")
print(sessionInfo())
devtools::session_info()
sink()
